// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOaEemDtysai0A3Sqe2_l5wUrRpU6mC3g',
    appId: '1:342612937365:web:df41ec0ed36e53574b299c',
    messagingSenderId: '342612937365',
    projectId: 'recicleme-4b731',
    authDomain: 'recicleme-4b731.firebaseapp.com',
    storageBucket: 'recicleme-4b731.firebasestorage.app',
    measurementId: 'G-MRJ0EZN9S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEEu7hwXG6qZiAqC9WV2yhv53ArBHxyjQ',
    appId: '1:342612937365:android:c897699c7c0e62814b299c',
    messagingSenderId: '342612937365',
    projectId: 'recicleme-4b731',
    storageBucket: 'recicleme-4b731.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOaEemDtysai0A3Sqe2_l5wUrRpU6mC3g',
    appId: '1:342612937365:web:7b4dc02c69d759c14b299c',
    messagingSenderId: '342612937365',
    projectId: 'recicleme-4b731',
    authDomain: 'recicleme-4b731.firebaseapp.com',
    storageBucket: 'recicleme-4b731.firebasestorage.app',
    measurementId: 'G-XZ8R4CMEG1',
  );
}
